services:

  db:
    build:
      context: ./postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d main"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      # - ./postgres:/docker-entrypoint-initdb.d/


    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    networks:
      - default
  backend:
      build:
        context: ./backend-fastapi
        
      ports:
        - 5000:5000
      depends_on:
        db:
          condition: service_healthy

      environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=main
        - POSTGRES_PORT=5432
        - POSTGRES_HOST=db
      volumes:
        - ./backend-fastapi/src:/app/src

      networks:
        - default
